### ISSUE TITLE
Failure classification of job aggregates

### ISSUE THREAD

**Issue by stuartphilp** [davehunt/fxtest-report#6]
At the job aggregate, colour the label red if the job has:

> 500 failures for most failures

> 30 minutes for slowest

> a day for longest running

**Comment by davehunt** [comment]
All the colours!

![screenshot-2017-7-5 firefox test engineering test results](https://user-images.githubusercontent.com/122800/27868433-92dfec44-6194-11e7-8dd9-a6a995ec68a6.png)
