### ISSUE TITLE
[bug] Python traceback "Value too large for defined data type" when generate.py runs

### ISSUE THREAD

**Issue by stephendonner** [davehunt/fxtest-report#7]
See https://qa-master.fxtest.jenkins.stage.mozaws.net/job/fxtest-report/2003/console - the job fails with:

```
[fxtest-report] Running shell script
+ cd /
+ python generate.py -o /out/index.html
Post stage
Traceback (most recent call last):
  File "generate.py", line 41, in <module>
    start = datetime.fromtimestamp(tddf['start'].min())
OSError: [Errno 75] Value too large for defined data type
```

**Comment by davehunt** [comment]
Thanks for reporting this @stephendonner it was because we had a hard-coded Jenkins URL from before the migration to CloudBees. I've fixed it and made some other improvements such as introducing a Jenkinsfile, switching to Pipfiles, and using the Dockerfile in Jenkins instead of Docker hub.
